apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: girus
    app: webserver
    service: webserver
  name: girus
spec:
  containers:
  - image: nginx
    name: girus
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
